### ISSUE TITLE
point to images in global-obis-es50 repo?

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/globe#8]
I believe we decided to have this application point to images that are hosted somewhere else. That somewhere else being https://github.com/USF-IMARS/global-obis-es50/tree/main/images/globe 

There are pros/cons to the different approaches. What we've done as of now is provided a single repository which has all the information and files needed to deploy this visualization tool, including the images we are creating. This provides a single package to get everything you need to run the thing making it somewhat stand alone. 

If we don't keep the images, and processing code to create the images, in this repo than we provide more provenance for that piece of the puzzle. As is documented in https://github.com/USF-IMARS/global-obis-es50. 

I'm not convinced enough to make the change to point to the images hosted out of the USF-IMARS repo. Could @albenson-usgs or @7yl4r convince me otherwise?

For reference, would need to adjust the url here to complete the change.
https://github.com/MathewBiddle/globe/blob/2325638273d0bece8297ec44fe4d9597bcfd9910/src/App.js#L48

**Comment by AbbyBenson** [comment]
I don't have strong opinions on this.

**Comment by 7yl4r** [comment]
My thinking here was to separate the code here that handles the display so that it could be more easily repurposed. But you are right that the way it is currently is cleaner than what I proposed. 

We don't need to put work into publishing a repurposable 3d-globe viewer; I was overengineering. We just need to make the separation of image-generation code from globe-display code clear in the README.

**Comment by MathewBiddle** [comment]
pointing to images in this repo.
